project:
  type: website
  output-dir: docs

website:
  title: Prof. VRK
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "About Me"
        file: about.qmd
    right: 
      - icon: github
        href: https://github.com/professorvrk
format:
  html:
    theme: cosmo
    css: styles.css



